### ISSUE TITLE
Tests! Different kinds!

### ISSUE THREAD

**Issue by crianonim** [fac-17/Week6-DFIO#24]
Well done for doing the tests for db and other parts of your system

**Comment by tloth** [comment]
the mere number of db tests are _marvellous_
if you get the chance, it would be lovely to see a couple server tests as well!

**Comment by tloth** [comment]
also, failing tests are sick, *CHALLENGE* for the next two hours (if you have spare time, again, very reasonable): make the 12 tests pass!
