### ISSUE TITLE
good planning & team work!

### ISSUE THREAD

**Issue by tloth** [fac-17/Week6-DFIO#31]
Maybe it's just that you get along, but it is lovely too see such smooth project planning!
You agreed on your idea, then made a viable plan which you then followed.
10 points for swapping pairs, and another 10 points for taking breaks!
The project may not be completely finished, but it seems you have learned a lot. (And there maaay be an opportunity to keep working on this project...)
Well done :sparkles:
![alex approves](https://66.media.tumblr.com/63022f71af2bc26332856a96a9d82ea8/tumblr_inline_mzb5v0Sp5t1s8x9ng.gif)

**Comment by tonylomax** [comment]
Thanks!  😄
