### ISSUE TITLE
Tip to increase security 

### ISSUE THREAD

**Issue by LaLeonie** [fac-17/Week6-DFIO#33]
In your queries, it's safer to use $1, $2 notations instead of string literals. It will save you better from malicious user input i.e. when a user tries to end the string literal and add SQL commands with their input. 

Her is what I mean with $ notations instead of string literals:
<img width="747" alt="Screenshot 2019-08-09 at 10 30 06" src="https://user-images.githubusercontent.com/45558475/62769375-b8344100-ba90-11e9-91fa-c71bc03ab251.png">

**Comment by tloth** [comment]
I remember you actually implemented this, maybe it's on a not-yet-merged branch :thinking:
